### ISSUE TITLE
Sensitivity issues

### ISSUE THREAD

**Issue by Xerasin** [CapsAdmin/wowozela#13]
People feel like the current sensitivity is too extreme for a lot of people and would prefer a ConVar for it

**Comment by CapsAdmin** [comment]
The sensitivity is supposed to obey the "senstivity" convar and feel unnoticeable. The way I do that obviously doesn't work. `sensitivity / 5` felt right to me but I'm probably missing something. We should look at how source engine does it to make it feel correct.

I don't think introducing a new sensitivity convar so that they can tune it themselves is a good solution.

**Comment by Xerasin** [comment]
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/client/in_mouse.cpp#L484

I think I got it accurate, turns out sensitivity scaling happens BEFORE InputMouseApply
